### PR TITLE
Better support for exams without grade

### PR DESCRIPTION
**Pull request by eltos**
- State labels for exams without grade (using common abbreviations):
  - AN (angemeldet) for registered exams
  - BE (bestanden) for passed exams
  - NB (nicht bestanden) for failed exams
  - EN (entgültig nicht bestanden) for permanently failed exams
- Grades in overview coloured (optional)

screenshot_20171015-182158

### CODE REVIEW

**Comment by tilmanginzel** [comment]
Hey @eltos,

thank you for your pull request! I like the idea and I'm quite sure we are going to merge this. I quickly skimmed through the implementation and it also looks good. 

There's only a minor thing I would like to change. It's possible that some people don't like the colors, so a setting where you could toggle them would be nice. One single on/off switch for all of them would be sufficient I guess. The color codes could be on as a default. If you want I can implement the setting, but feel free if you want to do it. ;)

We're quite busy at the moment so please give us some time to properly test, merge and publish it. I suppose it may take at least another month.

Cheers. :)

**Comment by eltos** [comment]
Thanks for the fast response.
An option to disable the colors is quickly done - I'll push a commit shortly ;)

**Comment by tilmanginzel** [comment]
Thanks for the quick patch @eltos! Due to our incredibly slow internet service providers, I _still_ have no internet connection at home to test this and publish a new version, so I'm afraid it will take another couple of weeks.

**Comment by eltos** [comment]
Hey there,

this is a friendly reminder that this request has now been open for four months.

Will there be a new release anytime soon?

Cheers

**Comment by tilmanginzel** [comment]
Hi @eltos,

my apologies for being so slow. It took my internet provider 2.5 months to provide me an internet connection, luckily that is resolved since the beginning of this year, so that excuse is now invalid. As I am not a student anymore, I am currently waiting for a friend to provide me temporary access to his account, so I can test and merge this. I actually set up Android Studio yesterday. ;)

I hope it will not take longer then another week.

Cheers.

**Comment by eltos** [comment]
I have successfully tested it with my personal student account before opening the merge request (which I think is needless to say) and been using my "debug"-version since. But I can understand that you want to test it yourself before publishing.
Thank's for your effort

**Comment by tilmanginzel** [comment]
Hi,

I just published a new version 1.2.1 to the Play Store. It should be available in a couple of hours. Thanks again for the pull request and sorry for the long delay!

Cheers :)

**Pull request merged**
